[2019-02-13 13:57:26,045]-[upload_cases.py]-INFO: 项目名称为：对象存储,对应的项目ID为：1
[2019-02-13 13:57:41,828]-[upload_cases.py]-INFO: 项目名称为：对象存储,对应的项目ID为：1
[2019-02-13 13:58:35,920]-[upload_cases.py]-INFO: 开始执行脚本
[2019-02-13 13:58:36,907]-[upload_cases.py]-INFO: 指定的用例集名称为：存储桶基本操作
[2019-02-13 13:58:36,907]-[upload_cases.py]-INFO: 开始读取Excel中的用例数据
[2019-02-13 13:58:36,923]-[upload_cases.py]-INFO: 指定Excel文档中总共有4条用例
[2019-02-13 13:58:36,923]-[upload_cases.py]-INFO: 读取数据完毕，开始解析数据
[2019-02-13 13:58:36,923]-[upload_cases.py]-INFO: 导入用例--创建存储桶1
[2019-02-13 13:58:36,923]-[upload_cases.py]-ERROR: 用例集中已经存在相同的用例名，请重新检查
[2019-02-13 13:58:36,923]-[upload_cases.py]-INFO: 导入用例--创建存储桶4
[2019-02-13 13:58:36,923]-[upload_cases.py]-ERROR: 用例集中已经存在相同的用例名，请重新检查
[2019-02-13 13:58:36,923]-[upload_cases.py]-INFO: 导入用例--创建存储桶2
[2019-02-13 13:58:36,923]-[upload_cases.py]-ERROR: 用例集中已经存在相同的用例名，请重新检查
[2019-02-13 13:58:36,923]-[upload_cases.py]-INFO: 导入用例--创建存储桶3
[2019-02-13 13:58:36,924]-[upload_cases.py]-ERROR: 用例集中已经存在相同的用例名，请重新检查
[2019-02-13 13:58:36,924]-[upload_cases.py]-INFO: 本次操作共提交4条数据，成功导入0条，失败4条
